window.BuahWira=window.BuahWira||{};BuahWira.game={save:BuahWira.Storage.read(),lang:'zh',level:1,score:0,lives:3,consecutiveWrongAnswers:0,totalAttempts:0,totalWrongAttempts:0,mastered:new Set(),pending:[],retry:[],fruits:[],halves:[],particles:[],slashes:[],state:'home',locked:false,last:0,pointer:null,
start(){this.score=0;this.lives=3;this.consecutiveWrongAnswers=0;this.totalAttempts=0;this.totalWrongAttempts=0;this.mastered=new Set();this.level=1;this.beginLevel(1)},beginLevel(n){this.level=n;this.consecutiveWrongAnswers=0;this.pending=BuahWira.questions.filter(q=>q.level===n).sort(()=>Math.random()-.5);this.retry=[];this.clearObjects();this.next()},clearObjects(){this.fruits=[];this.halves=[];this.particles=[];this.slashes=[];this.pointer=null;clearTimeout(this.timer)},next(){let q=this.pending.shift()||this.retry.shift();if(!q)return this.complete();this.q=q;this.state='reading';this.locked=false;this.clearObjects();this.prepare();this.timer=setTimeout(()=>{if(this.state==='reading')this.spawn()},3500)},
prepare(){let t=BuahWira.t,m=[...this.mastered].filter(id=>BuahWira.questions.find(q=>q.id===id).level===this.level).length;this.map=this.q.a.map((option,i)=>({option,i})).sort(()=>Math.random()-.5).map((v,i)=>({...v,label:'ABCD'[i]}));BuahWira.UI.q('#stage').textContent=t(`第${this.level}关`,`Tahap ${this.level}`);BuahWira.UI.q('#progress').textContent=t(`已掌握 ${m}/5`,`Dikuasai ${m}/5`);BuahWira.UI.q('#hud').textContent=t(`分数 ${this.score}　生命 ${this.lives}　连续错误 ${this.consecutiveWrongAnswers}/3`,`Skor ${this.score}　Nyawa ${this.lives}　Salah berturut-turut ${this.consecutiveWrongAnswers}/3`);BuahWira.UI.q('#phase').textContent=t('阅读问题','Baca soalan');BuahWira.UI.q('#question').textContent=this.q[this.lang];BuahWira.UI.q('#answers').className='answers';BuahWira.UI.q('#answers').innerHTML=this.map.map(v=>`<div class="answer"><b>${v.label}</b>${v.option[this.lang]}</div>`).join('');let tip=BuahWira.UI.q('#tip');tip.style.display='block';tip.textContent=t('请阅读。答案水果将在 3 秒后飞出。','Baca dahulu. Buah jawapan akan muncul dalam 3 saat.')},
spawn(){this.state='playing';let w=innerWidth,h=innerHeight,types=[...BuahWira.Assets.fruitNames].sort(()=>Math.random()-.5).slice(0,4);this.fruits=this.map.map((v,i)=>({fruitType:types[i],optionLabel:v.label,optionIndex:v.i,x:w*(.17+i*.22),y:h+100,vx:(i-1.5)*24,vy:-500-i*24,rotation:0,radius:Math.max(50,Math.min(78,w*.09)),isSliced:false,isAnswerFruit:true}));BuahWira.UI.q('#phase').textContent=BuahWira.t('滑动切开答案水果','Leret untuk potong buah jawapan');BuahWira.UI.q('#tip').style.display='none';BuahWira.Audio.play(400)},
update(dt){if(this.state!=='playing'&&this.state!=='slicing')return;this.fruits.forEach(f=>{f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=620*dt;f.rotation+=dt});this.halves.forEach(h=>{h.x+=h.vx*dt;h.y+=h.vy*dt;h.vy+=620*dt;h.life-=dt});this.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt});this.halves=this.halves.filter(h=>h.life>0);this.particles=this.particles.filter(p=>p.life>0);if(this.state==='playing'&&this.fruits.length&&this.fruits.every(f=>f.y>innerHeight+150)){this.fruits=[];BuahWira.UI.q('#tip').textContent=BuahWira.t('答案水果将重新飞出。','Buah jawapan akan muncul semula.');setTimeout(()=>{if(this.state==='playing')this.spawn()},500)}},
draw(){let c=BuahWira.UI.q('#field'),d=devicePixelRatio||1,w=innerWidth,h=innerHeight,ctx=c.getContext('2d');if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)}ctx.clearRect(0,0,w,h);for(const f of this.fruits){let img=BuahWira.Assets.getFruit(f.fruitType);ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.rotation);ctx.drawImage(img,-f.radius,-f.radius,f.radius*2,f.radius*2);ctx.rotate(-f.rotation);ctx.fillStyle='#fff';ctx.strokeStyle='#542219';ctx.lineWidth=6;ctx.font=`bold ${f.radius*.7}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeText(f.optionLabel,0,5);ctx.fillText(f.optionLabel,0,5);ctx.restore()}for(const h2 of this.halves){let img=BuahWira.Assets.getFruit(h2.fruitType,h2.part);ctx.drawImage(img,h2.x-h2.radius,h2.y-h2.radius,h2.radius*2,h2.radius*2)}for(const p of this.particles){ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}for(const s of this.slashes){ctx.strokeStyle=`rgba(255,248,205,${s.life})`;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke();s.life-=.06}this.slashes=this.slashes.filter(s=>s.life>0)},
pointerDown(e){this.pointer={x:e.clientX,y:e.clientY};BuahWira.UI.q('#field').setPointerCapture?.(e.pointerId)},pointerMove(e){if(!this.pointer||this.state!=='playing'||this.locked)return;let a=this.pointer,b={x:e.clientX,y:e.clientY};if(Math.hypot(b.x-a.x,b.y-a.y)>8){this.slashes.push({x1:a.x,y1:a.y,x2:b.x,y2:b.y,life:1});this.hit(a,b);this.pointer=b}},pointerUp(){this.pointer=null},hit(a,b){for(const f of this.fruits){let dx=b.x-a.x,dy=b.y-a.y,u=Math.max(0,Math.min(1,((f.x-a.x)*dx+(f.y-a.y)*dy)/(dx*dx+dy*dy||1)));if(!f.isSliced&&Math.hypot(f.x-(a.x+dx*u),f.y-(a.y+dy*u))<f.radius){this.slice(f);return}}},
slice(f){if(!f||f.isSliced||this.locked)return;f.isSliced=true;f.collisionEnabled=false;this.locked=true;this.state='slicing';BuahWira.Audio.playEffect('slice');this.fruits=[];for(const side of [['left',-1],['right',1]])this.halves.push({x:f.x,y:f.y,vx:side[1]*150,vy:-130,radius:f.radius,fruitType:f.fruitType,part:side[0],life:.5});for(let i=0;i<20;i++)this.particles.push({x:f.x,y:f.y,vx:(Math.random()-.5)*280,vy:-Math.random()*240,size:2+Math.random()*4,color:'#fff2a8',life:.6});setTimeout(()=>this.answer(f.optionIndex),420)},
answer(i){this.totalAttempts++;if(i===this.q.c){this.consecutiveWrongAnswers=0;this.mastered.add(this.q.id);this.score+=100;this.feedback(true)}else{this.totalWrongAttempts++;this.consecutiveWrongAnswers++;this.lives=Math.max(0,this.lives-1);if(this.consecutiveWrongAnswers>=3||this.lives<=0){this.failLevel();return}this.retry.push(this.q);this.feedback(false)}},feedback(ok){this.state='feedback';let t=BuahWira.t,q=this.q,notice=ok?'+100':this.consecutiveWrongAnswers===1?t('答错了！连续错误 1/3','Jawapan salah! Kesalahan berturut-turut 1/3'):t('再小心一点！连续错误 2/3','Berhati-hati! Kesalahan berturut-turut 2/3');BuahWira.UI.dialog(`<h2>${ok?t('回答正确！','Jawapan betul!'):t('答案不正确','Jawapan belum tepat')}</h2><p>${notice}</p><p><b>${t('正确答案：','Jawapan betul: ')}</b>${q.a[q.c][this.lang]}</p><p>${q.e[this.lang]}</p><button type="button" id="go">${t('继续','Teruskan')}</button>`);BuahWira.UI.q('#go').onclick=()=>{BuahWira.UI.close();this.next()}},failLevel(){this.state='LEVEL_FAILED';this.locked=true;this.clearObjects();let t=BuahWira.t,mastered=[...this.mastered].filter(id=>BuahWira.questions.find(q=>q.id===id).level===this.level).length;BuahWira.UI.dialog(`<h2>${t('本关挑战失败','Cabaran Tahap Gagal')}</h2><p>${t('你已经连续切错3次答案，请重新挑战本关。','Anda telah memotong tiga jawapan yang salah secara berturut-turut. Sila cuba semula tahap ini.')}</p><p>${t('已掌握题目：','Soalan dikuasai: ')}${mastered}/5<br>${t('尚未掌握：','Belum dikuasai: ')}${5-mastered}<br>${t('总尝试次数：','Jumlah percubaan: ')}${this.totalAttempts}<br>${t('错误尝试次数：','Percubaan salah: ')}${this.totalWrongAttempts}<br>${t('连续错误：3/3','Kesalahan berturut-turut: 3/3')}</p><button type="button" id="restartLevel">${t('重新开始本关','Mulakan Semula Tahap')}</button><button type="button" id="backHome">${t('返回主页','Kembali ke Halaman Utama')}</button>`);BuahWira.UI.q('#restartLevel').onclick=()=>{BuahWira.UI.close();this.lives=3;this.consecutiveWrongAnswers=0;this.mastered=new Set([...this.mastered].filter(id=>BuahWira.questions.find(q=>q.id===id).level!==this.level));this.beginLevel(this.level)};BuahWira.UI.q('#backHome').onclick=()=>{BuahWira.UI.close();BuahWira.UI.q('#play').hidden=true;BuahWira.UI.q('#home').hidden=false;this.consecutiveWrongAnswers=0;this.clearObjects()}},
complete(){let n=[...this.mastered].filter(id=>BuahWira.questions.find(q=>q.id===id).level===this.level).length;if(n!==5)return this.next();if(this.level<3){BuahWira.UI.dialog(`<h2>${BuahWira.t('关卡完成！','Tahap selesai!')}</h2><button type="button" id="go">${BuahWira.t('下一关','Tahap seterusnya')}</button>`);BuahWira.UI.q('#go').onclick=()=>{BuahWira.UI.close();this.beginLevel(this.level+1)}}else{BuahWira.UI.dialog(`<h2>${BuahWira.t('最终胜利！','Kemenangan akhir!')}</h2><p>15/15 · ${this.score}</p><button type="button" id="go">${BuahWira.t('再玩一次','Main semula')}</button>`);BuahWira.UI.q('#go').onclick=()=>{BuahWira.UI.close();this.start()}}}};
const bwSpawn=BuahWira.game.spawn,bwUpdate=BuahWira.game.update,bwAnswer=BuahWira.game.answer;
BuahWira.game.updateTimerUI=function(){let n=Math.ceil(this.questionTimeRemaining),t=BuahWira.t;BuahWira.UI.q('#hud').textContent=t(`分数 ${this.score}　生命 ${this.lives}　剩余时间 ${n}秒　连续错误 ${this.consecutiveWrongAnswers}/3`,`Skor ${this.score}　Nyawa ${this.lives}　Masa ${n} saat　Salah berturut-turut ${this.consecutiveWrongAnswers}/3`);let bar=BuahWira.UI.q('.timer i');if(bar){bar.style.width=`${Math.max(0,this.questionTimeRemaining/30*100)}%`;bar.style.background=n<=5?'#d95038':n<=10?'#ed9d32':'linear-gradient(90deg,#f0d442,#8bc13d)'}};
BuahWira.game.spawn=function(){this.questionTimeRemaining=30;this.timerRunning=true;this.timerExpired=false;bwSpawn.call(this);this.updateTimerUI()};
BuahWira.game.update=function(dt){if(this.state==='playing'&&this.timerRunning&&!this.locked){this.questionTimeRemaining=Math.max(0,this.questionTimeRemaining-dt);this.updateTimerUI();if(this.questionTimeRemaining===0)this.handleQuestionTimeout()}bwUpdate.call(this,dt)};
BuahWira.game.answer=function(i){this.timerRunning=false;bwAnswer.call(this,i)};
BuahWira.game.handleQuestionTimeout=function(){if(this.locked||this.timerExpired)return;this.locked=true;this.timerExpired=true;this.timerRunning=false;this.totalAttempts++;this.totalWrongAttempts++;this.lives=Math.max(0,this.lives-1);this.clearObjects();if(this.lives<=0){this.failLevel();return}this.retry.push(this.q);this.state='feedback';let t=BuahWira.t,q=this.q;BuahWira.UI.dialog(`<h2>${t('时间到了！','Masa Tamat!')}</h2><p>${t('你没有在30秒内切出答案，本题判定为错误。','Anda tidak memotong sebarang jawapan dalam masa 30 saat. Soalan ini dianggap salah.')}</p><p>${t('这道题稍后会再次出现。','Soalan ini akan muncul semula kemudian.')}</p><p><b>${t('正确答案：','Jawapan betul: ')}</b>${q.a[q.c][this.lang]}</p><p>${q.e[this.lang]}</p><button type="button" id="go">${t('继续','Teruskan')}</button>`);BuahWira.UI.q('#go').onclick=()=>{BuahWira.UI.close();this.next()}};
const bwNextQuestion=BuahWira.game.next;
BuahWira.game.next=function(){this.timerStartedForQuestion=false;this.questionTimeRemaining=30;this.timerRunning=false;this.timerExpired=false;bwNextQuestion.call(this);this.updateTimerUI()};
BuahWira.game.stopQuestionClock=function(){this.timerRunning=false};
BuahWira.game.spawn=function(){const fresh=!this.timerStartedForQuestion;bwSpawn.call(this);if(fresh){this.timerStartedForQuestion=true;this.questionTimeRemaining=30;this.timerExpired=false;this.timerRunning=true;this.lastTimerSecond=30}this.updateTimerUI()};
BuahWira.game.update=function(dt){if(this.state==='playing'&&this.timerRunning&&!this.locked&&!this.timerExpired){this.questionTimeRemaining=Math.max(0,this.questionTimeRemaining-dt);this.updateTimerUI();if(this.questionTimeRemaining===0){this.timerRunning=false;this.timerExpired=true;this.handleQuestionTimeout()}}bwUpdate.call(this,dt)};
BuahWira.game.answer=function(i){this.timerRunning=false;bwAnswer.call(this,i)};
BuahWira.game.stopQuestionClock=function(){this.timerRunning=false;if(this.questionClock){clearInterval(this.questionClock);this.questionClock=null}};
BuahWira.game.startQuestionClock=function(){this.stopQuestionClock();this.questionTimeRemaining=30;this.timerRunning=true;this.timerExpired=false;this.clockStamp=Date.now();this.updateTimerUI();this.questionClock=setInterval(()=>{const now=Date.now();if(this.state!=='playing'||this.locked){this.clockStamp=now;return}const elapsed=(now-this.clockStamp)/1000;this.clockStamp=now;this.questionTimeRemaining=Math.max(0,this.questionTimeRemaining-elapsed);this.updateTimerUI();if(this.questionTimeRemaining<=0){this.stopQuestionClock();this.handleQuestionTimeout()}},100)};
BuahWira.game.spawn=function(){bwSpawn.call(this);this.startQuestionClock()};
BuahWira.game.answer=function(i){this.stopQuestionClock();bwAnswer.call(this,i)};
BuahWira.game.update=function(dt){if(this.state==='playing'&&this.timerRunning&&!this.locked&&!this.timerExpired){this.questionTimeRemaining=Math.max(0,this.questionTimeRemaining-dt);this.updateTimerUI();if(this.questionTimeRemaining===0){this.timerRunning=false;this.timerExpired=true;this.handleQuestionTimeout()}}bwUpdate.call(this,dt)};
BuahWira.game.spawn=function(){const newQuestion=!this.timerStartedForQuestion;bwSpawn.call(this);if(newQuestion){this.timerStartedForQuestion=true;this.questionTimeRemaining=30;this.timerExpired=false;this.timerRunning=true;this.updateTimerUI()}};
BuahWira.game.answer=function(i){this.timerRunning=false;if(this.questionClock){clearInterval(this.questionClock);this.questionClock=null}bwAnswer.call(this,i)};
// Audio feedback is applied once at the answer boundary, without changing answer flow.
const buahWiraAnswerWithAudio=BuahWira.game.answer.bind(BuahWira.game);
BuahWira.game.answer=function(optionIndex){BuahWira.Audio.playEffect(optionIndex===this.q.c?'correct':'wrong');return buahWiraAnswerWithAudio(optionIndex)};
